import { z } from 'zod'

export const DEFAULT_SEO_SCHEMA = z.object({
  title: z.string(),
  description: z.string(),
  keywords: z.array(z.string()),
  // metadataBase: z.string().url(),
  openGraph: z.object({
    type: z.string(),
    url: z.string(),
    title: z.string(),
    description: z.string(),
    locale: z.string(),
    siteName: z.string()
  }),
  twitter: z.object({
    card: z.string(),
    site: z.string(),
    title: z.string(),
    description: z.string()
  }),
  // applicationName: z.string(),
  // authors: z.array(z.object({ name: z.string(), url: z.string() })), ✅
  // generator: z.string(),
  // creator: z.string(), ✅
  // publisher: z.string(), ✅
  robots: z.string(), // index, follow
  // icons: z.object({ ✅
  //   icon: z.string(),
  //   apple: z.string()
  // }),
  category: z.string()
})

export const SEO_TAGS = [
  'title',
  'description',
  'keywords',
  'openGraph',
  'twitter',
  'robots',
  'category'
]

export const SEO_ITEMS_WITHOUT_AI = ['applicationName', 'authors', 'creator', 'publisher', 'icons']

export const DIRECTORIES_TO_IGNORE = [
  'node_modules',
  '.git',
  '.github',
  'logs',
  '.dvc',
  '.pytest_cache',
  '.svn',
  '.tox',
  '.vscode',
  '.idea',
  'assets',
  'data',
  'dist',
  'docs',
  'htmlcov',
  'imgs',
  'media',
  'static',
  'tests',
  'testing',
  '__tests__',
  'tools',
  '.DS_Store',
  'examples',
  'samples',
  'output',
  'out',
  '.next',
  'build',
  'tmp',
  '.husky',
  'release',
  '.devcontainer',
  '.changeset',
  'utils'
]

export const FILES_TO_IGNORE = [
  '.editorconfig',
  '.gitignore',
  '.npmignore',
  '.dockerignore',
  '.env',
  '.env.example',
  '.env.local',
  '.babelrc',
  '.dvcignore',
  '.flake8',
  '.git',
  '.gitattributes',
  '.gitkeep',
  '.gitlab-ci',
  '.gitmodules',
  '.pre-commit-config.yaml',
  '.project-root',
  '.whitesource',
  'AUTHORS',
  'CHANGELOG',
  'CODE_OF_CONDUCT',
  'CONTRIBUTING',
  'LICENSE',
  'LICENSE-APACHE',
  'LICENSE_APACHE-2.0',
  'LICENSE-MIT',
  'MANIFEST',
  'README',
  'README.md',
  'appimage',
  'bundle_dmg',
  'gradlew',
  'start',
  'test_binary',
  'mkdocs.yml',
  '.markdownlint.yml',
  'pnpm-lock.yaml',
  'pnpm-workspace.yaml',
  'tsconfig.json',
  '.eslintignore',
  '.eslintrc',
  '.eslintrc.js',
  '.eslintrc.json',
  '.eslintcache',
  '.nvmrc',
  '.prettierrc.js',
  '.prettierrc.json',
  '.prettierrc',
  '.prettierignore',
  'favicon',
  '__init__.py',
  'package.json',
  'package-lock.json',
  'yarn.lock',
  'jest.config.js',
  'karma.conf.js',
  'webpack.config.js',
  'rollup.config.js',
  'babel.config.js',
  'vite.config.js',
  'lerna.json',
  '.npmrc',
  'gulpfile.js',
  'Gruntfile.js',
  'vitest.config.ts',
  'turbo.json',
  'next.config.js',
  'tailwind.config.ts',
  'tailwind.config.js',
  'tsup.config.ts',
  '.turbo',
  'next-env.d.ts',
  'postcss.config.js'
]

export const OPTIONS_TAGS = [
  { value: 'core', label: 'Core SEO tags', hint: 'recommended' },
  { value: 'icons', label: 'Icons', hint: 'recommended' },
  { value: 'applicationName', label: 'Application Name' },
  { value: 'metadataBase', label: 'URL prefix for metadata fields' },
  { value: 'authors', label: 'Authors' },
  { value: 'creator', label: 'Creator' },
  { value: 'publisher', label: 'Publisher' },
  { value: 'classification', label: 'Classification' },
  { value: 'bookmarks', label: 'Bookmarks' },
  { value: 'assets', label: 'Assets' },
  { value: 'archives', label: 'Archives' },
  { value: 'referrer', label: 'Referrer' },
  { value: 'alternates', label: 'Canonical URL' },
  { value: 'formatDetection', label: 'Format Detection' },
  { value: 'manifest', label: 'Manifest' },
  { value: 'verification', label: 'Verification' },
  { value: 'viewport', label: 'Colors' }, // https://nextjs.org/docs/app/api-reference/functions/generate-viewport
  { value: 'generator', label: 'Generator used' }
]
